name: Build and Push to ACR

on:
    workflow_dispatch:
        inputs:
            c8-report-token:
              description: "C8 Report Token"

env:
  REGISTRY_NAME: acmefleets.azurecr.io
  IMAGE_NAME: acme-fleet-user-webapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY_NAME }}
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Report status back to C8
      run: |
        STARTED_AT=$(date -Iseconds)
        curl -X POST \
        -H "c8-report-token: ${{ inputs.c8-report-token }}" \
        -H "Content-Type: application/json" \
        https://app.configure8.io/self-service/api/v1/reports/webhook \
        -d "{ \"status\": \"complete\",  \"startedAt\": \"$STARTED_AT\"}" \